import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  // Fonction pour effectuer le swap (à implémenter)
  function performSwap() {
    // Code pour effectuer le swap ici
    alert('Swap performed successfully!');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Swapkirk</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Voulez-vous échanger vos cryptos ?
        </h1>

        {/* Section de swap */}
        <div className="swap-section">
          <div className="input-group">
            <label htmlFor="token1">Select Token 1:</label>
            <input type="text" id="token1" placeholder="Token 1" />
          </div>
          <div className="input-group">
            <label htmlFor="token2">Select Token 2:</label>
            <input type="text" id="token2" placeholder="Token 2" />
          </div>
          <button className="swap-button" onClick={performSwap}>
            Swap Tokens
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Elias
        </a>
      </footer>
    </div>
  );
};

export default Home;
